### PR TITLE
output comments

### PR DESCRIPTION
**Pull request by epicgirl1998**
<details><summary>output examples (click to show)</summary>

```typescript
/** @deprecated Event pages are not currently supported. This will run as a persistent background page. */
type PersistentBackgroundProperty = boolean;
```

```typescript
/**
 * Use the `browser.browserSettings` API to control global settings of the browser.
 * 
 * Permissions: `browserSettings`
 */
declare namespace browser.browserSettings { /* ... */ }
```

```typescript
/** Manifest keys: `optional_permissions` */
declare namespace browser.permissions { /* ... */ }
```

```typescript
/** A suggest result. */
interface DefaultSuggestResult {
    /** The text that is displayed in the URL dropdown. */
    description: string;
    /** An array of style ranges for the description, as provided by the extension. */
    descriptionStyles?: Array<{
        offset: number;
        /** The style type */
        type: DescriptionStyleType;
        length?: number;
    }>;
    /** An array of style ranges for the description, as provided by ToValue(). */
    descriptionStylesRaw?: Array<{
        offset: number;
        type: number;
    }>;
}

/* omnibox functions */
/**
 * Sets the description and styling for the default suggestion. The default suggestion is the text that is displayed in the first suggestion row underneath the URL bar.
 * @param suggestion A partial SuggestResult object, without the 'content' parameter.
 */
function setDefaultSuggestion(suggestion: DefaultSuggestResult): void;
```

etc etc

</details>

these things are included in comments when available:

- descriptions
- for namespaces: permissions and manifest keys
- for everything else: deprecation messages
- new: for functions, the descriptions of the parameters and the return value

questions:

- is there any place in the converter where a comment isn't outputted when it should be? i don't know of any but maybe you know the code better than i do
- do the comments display okay in editors other than vscode? especially function parameters, this isn't how you'd normally document them but it seems to work

### CODE REVIEW

**Comment by bomjacob** [comment]
This looks really really good, you even spent time on style consistency, amazing :D (admittedly some of the stylistic choices could probably be amended).
I do have a few minor comments:

- First of all the docs for the function parameters don't seem to work in my IDE (WebStorm), could we maybe revise them so they follow typescript guidelines (i think?) at [DocComments | TypeDoc](http://typedoc.org/guides/doccomments/)? (I know this sigificantly harder than what you've done already, so just say if you need help, and I'll take a crack at it)
- Currently we just filter links (like `$(ref:runtime.onConnect)` is there any way we can make them link to either the correct type/function/event using markdown? [DocComments | TypeDoc](http://typedoc.org/guides/doccomments/) suggests `[[double square brackets]]` (though it doesn't work in my IDE, how's it look in vscode?)

I don't think you missed any places that need comments :)

**Comment by bomjacob** [comment]
Actually it seems like the returns
```
"returns": {
          "$ref": "BlockingResponse",
          "description": "If \"blocking\" is specified in the \"extraInfoSpec\" parameter, the event listener should return an object of this type.",
          "optional": true
        }
```
from the onBeforeRequest event in web_request.json, has a description that isn't shown anywhere in the output.

**Comment by epicgirl1998** [comment]
> First of all the docs for the function parameters don't seem to work in my IDE (WebStorm), could we maybe revise them so they follow typescript guidelines (i think?) at DocComments | TypeDoc? (I know this sigificantly harder than what you've done already, so just say if you need help, and I'll take a crack at it)

i was going to do it the normal way first but i found out that easy way worked and went with it

i'll see if i can fix it

> Currently we just filter links (like $(ref:runtime.onConnect) is there any way we can make them link to either the correct type/function/event using markdown? DocComments | TypeDoc suggests [[double square brackets]] (though it doesn't work in my IDE, how's it look in vscode?)

i'd like to output links but i don't think vscode (or is it typescript?) supports code links like that either, i don't know what editor does

[jsdoc](http://usejsdoc.org/tags-inline-link.html) has some suggestions too but none of the methods on that page work in vscode

the most widely supported code link format should probably be used but i don't know what that would be

**Comment by bomjacob** [comment]
For now let's not worry about the linking then. Maybe open an issue so we don't forget.

**Comment by epicgirl1998** [comment]
return values and parameters should be properly commented now, but there are 1½ things to note:

```typescript
/**
 * Requests DevTools to open a URL in a Developer Tools panel.
 * @param url The URL of the resource to open.
 * @param lineNumber Specifies the line number to scroll to when the resource is loaded.
 */
const openResource: ((url: string, lineNumber: number) => Promise<void>) | undefined;

/* devtools.panels events */
/**
 * Fired when the devtools theme changes.
 * @param themeName The name of the current devtools theme.
 */
const onThemeChanged: WebExtEventListener<(themeName: string) => void>;
```

1. `openResource` here gets the comment, but its parameters don't because it can be `undefined`
   - idea: indicate unsupported things in the `@deprecated` comment instead, if it isn't present already?
2. the `themeName` comment doesn't apply to the parameter, but it seems like you can't really comment function/callback types anyway (in a way that's visible when using the function), not even with the old way of outputting the comments (it should output less of those useless comments now)

**Comment by bomjacob** [comment]
1. Yeah when it comes to unsupported types, we should definitely mark them as deprecated (especially since firefox in places do that themselves), you wanna fix that in this PR too?
2. Yeah it does indeed seem like that is the case. One fix could be to add the documentation to the `addListener`, but that would involve having a seperate event listener/handler for each and every event.

**Comment by bomjacob** [comment]
Should we add `allowedContexts` of functions/events to the comments too?

**Comment by epicgirl1998** [comment]
> Yeah when it comes to unsupported types, we should definitely mark them as deprecated (especially since firefox in places do that themselves), you wanna fix that in this PR too?

to clarify: i was asking about replacing `setUnsupportedAsOptional` with that, at least for functions since the parameters can't be commented otherwise

`setUnsupportedAsOptional` doesn't preserve the `unsupported` key and `deepMapKeys` only passes the key and its value to the callback so you can't easily exclude functions from it by checking the type

would removing it be ok? unless lodash has something similar that would work, i haven't used it before

maybe marking unsupported as optional is useful for other things like object properties or parameters?

> Should we add allowedContexts of functions/events to the comments too?

i thought of it too but not every schema has it and i'm not sure what the key even means (if the api is only supported in those contexts or something else?)

there are also values like `"addon_parent_only"` and `"proxy"` that i don't know what they are, and `"devtools", "devtools_only"` will have to be un-duplicated

**Comment by bomjacob** [comment]
I think the best thing we could do would be to mark everything that's unsupported as optional *unless* it's a *root* function, event or type.

It means that the method or event is only available in those scopes (will either give an error if used, or simply be `undefined` if attempted to use elsewhere).
I have no clue what `"addon_parent_only` means, the only I could find about it is [this](https://hg.mozilla.org/mozilla-central/rev/f2f75e6e2d60).
"Proxy" is whether it can be used in a proxy script (PAC) (see [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/proxy)).

**Comment by epicgirl1998** [comment]
> I think the best thing we could do would be to mark everything that's unsupported as optional unless it's a root function, event or type.

top-level functions are now never optional, and unsupported things get a deprecation message copied from an existing one

```typescript
/**
 * Prompt the user to either accept or cancel a dangerous download. `acceptDanger()` does not automatically accept dangerous downloads.
 * @param downloadId
 * @deprecated Unsupported on Firefox at this time.
 */
function acceptDanger(downloadId: number): void;
```

i thought optional events worked as well as they could already, and can't find any optional types (are they an issue?)

> Should we add allowedContexts of functions/events to the comments too?

the `allowedContexts` key is on namespaces, would it be enough to have it on the namespace declaration?

**Comment by bomjacob** [comment]
Yes those two changes definitely look good :D 
Got any more changes before i merge?

**Comment by epicgirl1998** [comment]
just the contexts thing

the `devtools_only` context makes the most sense to me since it's actually clear what it means

it only lists content scripts and devtools pages as allowed contexts for `browser.storage`, but you can also use it from background or options pages which aren't mentioned as contexts for anything

and `browser.webRequest` which probably isn't allowed from content scripts has no allowed contexts listed

or maybe content scripts and devtools pages can only use the apis where they're listed in `allowedContexts`? i'll have to edit the comment to also say something like `Not allowed in: <contexts>` then

```typescript
/**
 * Permissions: `devtools`
 * 
 * Contexts: Devtools pages only
 */
declare namespace browser.devtools {}
```

**Comment by bomjacob** [comment]
so you mean something like
`const ALL_CONTEXTS = set('devtools', 'content', 'proxy'...)`
and then output
`Not allowed in: ALL_CONTEXTS - additionalContexts`
?
(not actual code)
This might get annoying, as it will add a line to every single function (where most will just be `Not allowed in: ALL_CONTEXTS`.
I guess the additionaContexts is more like a "this function, unlike others, be extraordinarily used in these contexts: ...` or something?

**Comment by epicgirl1998** [comment]
> so you mean something like `...`

probably something like that

i don't know if the feature is useful enough to include it in every comment ever

you can already guess what kind of apis you can't use from content scripts or devtools pages since the restrictions make sense

i would be okay with adding it for namespaces, though it won't be perfect since functions and other things inside the namespace can also have `allowedContexts` so not everything inside the namespace might actually be usable in the context

**Comment by bomjacob** [comment]
yeah adding it only for namespaces would make good sense :)

**Comment by epicgirl1998** [comment]
conflict is fixed, and it comments some more contexts now:

<details><summary>examples (click to show)</summary>

```typescript
/**
 * Permissions: `devtools`
 * 
 * Allowed in: Devtools pages only
 */
declare namespace browser.devtools {}
```

```typescript
/**
 * Use the `browser.runtime` API to retrieve the background page, return details about the manifest, and listen for and respond to events in the app or extension lifecycle. You can also use this API to convert the relative path of URLs to fully-qualified URLs.
 * 
 * Allowed in: Proxy scripts
 */
declare namespace browser.runtime { /* ... */ }
```

```typescript
/**
 * Request the given permissions.
 * 
 * Not allowed in: Devtools pages
 * @param permissions
 */
function request(permissions: Permissions): Promise<boolean>;
```

```typescript
/**
 * Use the `browser.webRequest` API to observe and analyze traffic and to intercept, block, or modify requests in-flight.
 * 
 * Permissions: `webRequest`
 * 
 * Not allowed in: Content scripts, Devtools pages
 */
declare namespace browser.webRequest { /* ... */ }
```

</details>

- content scripts and devtools pages are commented as "not allowed in" whenever not included in `allowedContexts`
- proxy scripts are so rare they're only commented as "allowed in" when they're included in the contexts
  - i hope this doesn't make it seem like the thing is only allowed in proxy scripts?
- namespaces always get a comment with contexts, while other things only get it if they have some `allowedContexts` defined

**Comment by bomjacob** [comment]
Yes, this looks really good now! :D 

> i hope this doesn't make it seem like the thing is only allowed in proxy scripts?

Hmm, I don't think so. I think we're fine :)

Merging... (though github says there are still conflicts, I can quickly resolve them though)

**Comment by bomjacob** [comment]
@epicgirl1998 I just noticed something that we should maybe fix too.

`browser.alarms.create` has two declarations, but since only the first one has the comment my IDE doesn't seem to provide any info from the comment at all.

Simple fix would be to add the comment once again after outputting an alternative function signature.
How does vscode handle this kind of thing?

**Pull request merged**
